### Request recover password [POST /v1/users/recover]
Request a recovery password, regardless of whether or not he will return 204

+ Request (application/json)
    + Attributes
        <!-- include(../../requests/userRecoverStore.apib) -->

+ Response 204 (application/json)
