+ title: Launch Devs (string, required)
+ description: New idea to generate jobs for rocketseat students  (string, required)
+ sub_title: Where is your rocket going? (string, required)
+ contact: `(11) 10101-0110` (string, required)
+ category_id: 424d0478-60e1-4301-8556-6918b9250c28 (UUID, required)
+ first_comment: Welcome to my idea, would you like to be part? (string, required)
+ status: execution (string, required)
