+ id: 424d0478-60e1-4301-8556-6918b9250c28 (UUID)
+ title: Launch Devs (string)
+ description: New idea to generate jobs for rocketseat students  (string)
+ sub_title: Where is your rocket going? (string)
+ contact: `11 10101-0110` (string)
+ first_comment: Welcome to my idea, would you like to be part? (string)
+ status: execution (string)
+ author_id: 9aa8edcd-047e-47e3-810e-a372f69b1ac8 (UUID)
+ category_id: 424d0478-60e1-4301-8556-6918b9250c28 (UIID)
+ updatedAt: 2019-11-03T20:05:16.003Z
+ createdAt: 2019-11-03T20:05:16.003Z
+ cover_id: null
+ thumbnail_id: null
