### Create idea [POST /v1/ideas]
Create a new user

+ Request (application/json)
    + Attributes
        <!-- include(../../requests/ideaStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/ideaStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
