# Group Sessions

## Sessions [/v1/sessions]

### Store [POST]
Login user

+ Request (application/json)
    + Attributes
        <!-- include(requests/sessionStore.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(responses/sessionStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(util/errorValidation.apib) -->
